### ISSUE TITLE
Remove symbols 

### ISSUE THREAD

**Issue by mouchi32** [AzeriteTeam/DiabolicUI#10]
Hi,

I don't know how to remove icons in the middle of the screen... Is it possible to do it and how ?

Thanks in advance !

<img width="766" alt="Capture d’écran 2019-12-11 à 13 14 28" src="https://user-images.githubusercontent.com/58775095/70620679-3019a000-1c18-11ea-95aa-3c514ed19292.png">

**Comment by goldpaw** [comment]
Yeah. You have to disable the addon SImpleClassPower. Because those are from that. Has nothing to do with DiabolicUI. :)

**Comment by mouchi32** [comment]
thanks a lot !
