### ISSUE TITLE
3 lua errors, disables keyboard completely

### ISSUE THREAD

**Issue by allyareus** [AzeriteTeam/DiabolicUI#3]
Message: Interface\AddOns\DiabolicUI\handlers\popups.lua:550: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
Time: Thu Jun 27 21:24:45 2019
Count: 1
Stack: Interface\AddOns\DiabolicUI\handlers\popups.lua:550: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
[C]: in function `SetPoint'
Interface\AddOns\DiabolicUI\handlers\popups.lua:550: in function `ShowPopUp'
Interface\AddOns\DiabolicUI\modules\chat\windows.lua:775: in function `PositionChatFrames'
Interface\AddOns\DiabolicUI\modules\chat\windows.lua:834: in function `OnEnable'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:1009: in function `func'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:891: in function <Interface\AddOns\DiabolicUI\engine\engine-core.lua:883>
(tail call): ?
Interface\AddOns\DiabolicUI\engine\engine-core.lua:1657: in function `ForAll'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:2074: in function `?'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:330: in function <Interface\AddOns\DiabolicUI\engine\engine-core.lua:317>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "LEFT"
_______________________________________________________________________________________________
Message: Interface\AddOns\DiabolicUI\handlers\popups.lua:550: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
Time: Thu Jun 27 21:24:46 2019
Count: 6
Stack: Interface\AddOns\DiabolicUI\handlers\popups.lua:550: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
[C]: in function `SetPoint'
Interface\AddOns\DiabolicUI\handlers\popups.lua:550: in function `ShowPopUp'
Interface\AddOns\DiabolicUI\modules\chat\windows.lua:775: in function `?'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:389: in function <Interface\AddOns\DiabolicUI\engine\engine-core.lua:317>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "LEFT"
______________________________________________________________________________
Message: ...\AddOns\DiabolicUI\modules\nameplates\nameplates.lua:1926: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
Time: Thu Jun 27 21:26:27 2019
Count: 2
Stack: ...\AddOns\DiabolicUI\modules\nameplates\nameplates.lua:1926: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
[C]: in function `SetPoint'
...\AddOns\DiabolicUI\modules\nameplates\nameplates.lua:1926: in function `CreateSizer'
...\AddOns\DiabolicUI\modules\nameplates\nameplates.lua:1982: in function `CreateNamePlate'
...\AddOns\DiabolicUI\modules\nameplates\nameplates.lua:2043: in function `?'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:389: in function <Interface\AddOns\DiabolicUI\engine\engine-core.lua:317>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
 Point = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1330
 Place = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1304
 CreateTexture = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1385
 CreateFontString = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1381
 CreateStatusBar = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1371
 CreateOrb = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1365
 worldFrame = WorldFrame {
 }
 CreateFrame = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1377
 plate = EngineNamePlate2 {
 }
 Size = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1350
}
(*temporary) = "TOPRIGHT"
(*temporary) = NamePlate2 {
 OnSizeChanged = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:458
 GetPreferredInsets = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:439
 GetAdditionalInsetPadding = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:428
 ApplyOffsets = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:410
 OnRemoved = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:397
 OnAdded = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:374
 UnitFrame = NamePlate2UnitFrame {
 }
 0 = <userdata>
 OnOptionsUpdated = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:404
}
(*temporary) = "CENTER"
(*temporary) = 0
(*temporary) = 0

**Comment by goldpaw** [comment]
Yeah, Diabolic is full of these. Haven't updated it for 8.2.0 yet. Will do in the upcoming days!

**Comment by goldpaw** [comment]
Fixed in 1.3.149-Release!
