### ISSUE TITLE
Bug and HUD Scale error

### ISSUE THREAD

**Issue by 40P3** [AzeriteTeam/DiabolicUI#4]
Logging in with DK to 8.2:

1399x FrameXML\GameTooltip.lua:154: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[C]: in function `SetPoint'
FrameXML\GameTooltip.lua:154: in function <FrameXML\GameTooltip.lua:152>
[C]: ?
[C]: in function `GameTooltip_SetDefaultAnchor'
[string "*:OnTooltipSetDefaultAnchor"]:1: in function <[string "*:OnTooltipSetDefaultAnchor"]:1>
[C]: ?

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
 comparing = false
 default = 1
 ItemTooltip = <unnamed> {
 }
 SetCurrencyToken = <function> defined =[C]:-1
 SetShapeshift = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
 SetVoidItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetToyByItemID = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
 SetQuestCurrency = <function> defined =[C]:-1
 ttGradient = <unnamed> {
 }
 ClearLines = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 ARKTTD = <table> {
 }
 Show = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetPetAction = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetCurrencyByID = <function> defined =[C]:-1
 ttIcon = <unnamed> {
 }
 SetTrainerService = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetAuctionItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
 SetTradePlayerItem = <function> defined =[C]:-1
 SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
 SetSendMailItem = <function> defined =[C]:-1
 FadeOut = <function> defined =[C]:-1
 updateTooltip = 0.142000
 SetInventoryItem = <function> defined =[C]:-1
 TMW_SetSpellByIDWithClassIcon = <function> defined @TellMeWhen\Components\Core\Spells\ClassSpellCache.lua:212
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetQuestLogCurrency = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = "UIParent"
(*temporary) = "BOTTOMRIGHT"
(*temporary) = -13
(*temporary) = 130

**Comment by 40P3** [comment]
Latest downloadable version from Twitch.

**Comment by goldpaw** [comment]
DiabolicUI-related bugs of this sort should be fixed from 1.3.149-Release.
