### ISSUE TITLE
21:9 @ 3440x1440

### ISSUE THREAD

**Issue by DeathAdder71** [AzeriteTeam/DiabolicUI#5]
Edit: I should've read the **Notes** before posting ... plz ignore this issue ... can't wait for v2 :-)

My monitor is 3440x1440 ... The UI components used to fit the edges of the screen in the old builds, but this last build (1.3.147) seems to be set for 2650x1440 only ... I tried to relocate some of the components by editing some of the lua files, but for the life of me, I can't set the chat window to the far left of the screen

Fantastic Addon with great Quality ... tbh I can't play without it ... I really wish you could make it configurable / drag-able like the good old GoldpawUI (or RothUI)

Thanks

**Comment by goldpaw** [comment]
We'll get a fix for the narrow ratio that started happening after 8.2.0 out tomorrow'ish, I hope. 

As for draggable items, to a certain degree they will be in DiabolicUI2. I have no ETA on that, but at least I'll get in the (hopefully) last 8.2.0 fixes tomorrow!

**Comment by goldpaw** [comment]
Is it fixed in 1.3.149-Release? Just uploaded it with scaling changes, and it should be available on CurseForge some minutes after writing this, Twitch a bit later. :o

**Comment by DeathAdder71** [comment]
Confirming, it has been fixed :-)

Side notes:
- Everything DiabolicUI is larger (as if zoomed), compared to older builds
- Twitch still says: Game Version 8.1.0

Best Regards

(Sorry for the late reply, was a hectic day at work)

**Comment by goldpaw** [comment]
Well Twitch is clearly drunk, because Curse knows it's for 8.2.0! ;) 

Good to hear it's been solved! Closing this.  

![Screenshot from 2019-07-03 14-04-25](https://user-images.githubusercontent.com/6476535/60590024-38350000-9d9b-11e9-8617-533dcc99e505.png)
